[package]
name = "updater"
version = "0.1.0"
authors = ["dmitry.astafyev <dmitry.astafyev@esrlabs.com>"]
edition = "2018"

[dependencies]
flate2 = "1.0.11"
tar = "0.4.26"
dirs = "2.0.2"
chrono = "0.4.7"
log = "0.4.8"
log4rs = "0.8.3"