[package]
name = "plugin-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.83"
log = "0.4.21"
wasmtime = "20.0.2"
parsers = {path = "../../parsers"}
serde = "1.0"
