package host:parse;


interface parsing {
  record parse-return {
    value: option<parse-yield>,
    cursor: u64,
  }

  record attachment {
    name: string,
    size: u64,
    created-date: option<string>,
    modified-date: option<string>,
    messages: list<u64>,
    data: list<u8>,
  }


  variant parse-yield {
    message(string),
    attachment(attachment),
    message-and-attachment(tuple<string, attachment>),
  }

  variant error {
    parse(string),
    incomplete,
    eof,
  }

  resource parser {
    constructor();
    parse: func(data: list<u8>, timestamp: option<u64>) -> list<result<parse-return, error>>;
  }
}

world parse {
    export parsing;
}
