[workspace]

[package]
name = "file_source"
version = "0.1.0"
edition = "2021"
authors = ["Ammar Abou Zor <ammar.abou.zor@accenture.com>"]
description = "An example of a Chipmunk bytesource plugin that reads byte data from a file and provides it to the Chipmunk application."

[dependencies]
# TODO AAZ: Use lib from crates.io once the crate is published
plugins_api = {path = "../../application/apps/indexer/plugins_api", features = ["bytesource"]}

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = true
lto = true

[package.metadata.component]
package = "component:file-source"
