[package]
name = "stypes"
description = "Shared types"
version = "0.1.0"
edition = "2021"

[features]
# This feature needed to be activated to generate the typescript types from rust type and to run the proptests on them.
# NOTE: The path for the generated type is set via the environment variable `TS_RS_EXPORT_DIR` which set in 
# `.cargo/config.toml` file in this crate.
test_and_gen = []
rustcore = [
    "dep:tokio",
    "dep:walkdir",
    "dep:regex",
    "dep:envvars",
    "dlt-core/statistics",
    "dlt-core/serde-support",
]
nodejs = [
    "dep:node-bindgen"
]

[dependencies]
serde = { workspace = true , features = ["derive"] }
dlt-core = { workspace = true, features = ["serde-support"] }
regex = { workspace = true, optional = true }
bincode = "1.3"
extend = { path = "../tools/extend"}
uuid = { workspace = true, features = ["serde"] }
tokio = { workspace = true, optional = true }
node-bindgen = { git = "https://github.com/infinyon/node-bindgen.git", branch="master", optional = true}
thiserror.workspace = true
walkdir = { workspace = true, optional = true }
envvars = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true  }
walkdir = { workspace = true }
node-bindgen = { git = "https://github.com/infinyon/node-bindgen.git", branch="master"  }
proptest = "1.5"
paste = "1.0"
uuid = { workspace = true, features = ["serde", "v4"] }
remove_dir_all = "1.0"
ts-rs = { version = "10.1", features = ["uuid-impl"] }

# Proptest and its random number generator can be CPU intensive, therefore setting their optimizations level 
# to max will have significant performance improvement for the tests.
[profile.test.package.proptest]
opt-level = 3

[profile.test.package.rand_chacha]
opt-level = 3
