[package]
name = "sources"
authors = ["esrlabs.com"]
version.workspace = true
edition.workspace = true

[lints]
workspace = true 

[dependencies]
async-stream = "0.3"
bufread.workspace = true
bytes = "1.3"
etherparse = "0.16"
futures.workspace = true
indexer_base.workspace = true
log.workspace = true
parsers.workspace = true
pcap-parser = "0.16"
thiserror.workspace = true
tokio.workspace = true
tokio-serial = "5.4"
tokio-stream.workspace = true
tokio-util = { workspace = true , features = ["full"] }
serde = { workspace = true, features = ["derive"] }
uuid = { workspace = true , features = ["serde", "v4"] }
regex.workspace = true
lazy_static.workspace = true
shellexpand = "3.1"
stypes = { workspace = true, features=["rustcore"] }
socket2 = "0.5.8"

[dev-dependencies]
env_logger.workspace = true
