[package]
name = "cargo-chipmunk"
version = "0.1.0"
edition = "2021"
description = "Tool for chipmunk application development"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
async-trait = "0.1.73"
clap = { version = "4.4.4", features = ["derive"] }
console = "0.15.7"
fs_extra = "1.3.0"
futures = "0.3.28"
futures-lite = "1.13.0"
git2 = "0.18.2"
indicatif = "0.17.7"
tokio = { version = "1.36.0", features = ["full"] }
