[package]
name = "dlt-tools"
version.workspace = true
edition.workspace = true

[lints]
workspace = true 

[dependencies]
dlt-core.workspace = true
indexer_base.workspace = true
log.workspace = true
parsers.workspace = true
sources.workspace = true
processor.workspace = true
tokio = { workspace = true , features = ["full"] }
tokio-util = { workspace = true, features = ["codec", "net"] }

[dev-dependencies]
