[package]
name = "node-bindings"
version = "0.1.0"
authors = ["Oliver Mueller <oliver.mueller@esrlabs.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
node-bindgen = {git = "https://github.com/marcmo/node-bindgen.git",branch = "without_logging_init_4.4.0" , features = ["build"] }

[dependencies]
anyhow = "1.0"
crossbeam-channel = "0.5"
ctor = "0.1.6"
dirs = "4.0"
indexer_base = { path = "../../indexer/indexer_base" }
log = "0.4"
log4rs = "1.0.0"
merging = { path = "../../indexer/merging" }
node-bindgen = {git = "https://github.com/marcmo/node-bindgen.git", branch = "without_logging_init_4.4.0", features = [] }
processor = { path = "../../indexer/processor" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.5", features = ["full"] }
tokio-util = "0.6"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
