[package]
name = "session"
authors = ["esrlabs.com"]
version.workspace = true
edition.workspace = true

[lints]
workspace = true 

[dependencies]
blake3.workspace = true
crossbeam-channel.workspace = true
dirs.workspace = true
dlt-core = { workspace = true, features = ["statistics", "serialization"] }
envvars = { workspace = true }
file-tools.workspace = true
futures.workspace = true
indexer_base.workspace = true
lazy_static.workspace = true
log.workspace = true
merging.workspace = true
mime_guess = "2.0"
parsers.workspace = true
processor.workspace = true
rustc-hash = "2.1"
stypes = { workspace = true, features=["rustcore"] }
serde = { workspace = true , features = ["derive"] }
serde_json.workspace = true
serialport = "4.6"
sources.workspace = true
thiserror.workspace = true
tokio = { workspace = true , features = ["full"] }
tokio-stream.workspace = true
tokio-util.workspace = true
uuid = { workspace = true , features = ["serde", "v4"] }
walkdir.workspace = true
plugins_host.workspace = true

[dev-dependencies]
lazy_static.workspace = true
tempfile.workspace = true
insta.workspace = true
