[[bench]]
name = "map_benchmarks"
library = "processor"

[[bench]]
name = "dlt_producer"
library = "processor"

[[bench]]
name = "someip_producer"
library = "processor"

[[bench]]
name = "someip_legacy_producer"
library = "processor"

[[bench]]
name = "text_producer"
library = "processor"

[[bench]]
name = "plugin_praser_producer"
library = "processor"

[[bench]]
name = "mocks_once_producer"
library = "processor"

[[bench]]
name = "mocks_once_parallel"
library = "processor"

[[bench]]
name = "mocks_multi_producer"
library = "processor"

[[bench]]
name = "mocks_multi_parallel"
library = "processor"

[[bench]]
name = "plugin_parser_init"
library = "plugins_host"
